### ISSUE TITLE
微信小程序input插槽无法自定义内容只能放图标

### ISSUE THREAD

**Issue by clarehjh** [yang1206/uniapp-nutui#21]
![image](https://github.com/yang1206/uniapp-nutui/assets/83281667/a13fba6a-f6c0-40b6-9235-3efaf722f90a)
![image](https://github.com/yang1206/uniapp-nutui/assets/83281667/5a29f24d-0807-4ab5-a6a9-1b717c98273b)

**Comment by yang1206** [comment]
下个版本修复，临时的解决方案就是重置掉左边字体样式
```scss
::v-deep .nut-input-left-box{
    font-size: 14px;
 }
```
